name: Pull-Requests Check

on: [pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 12

    - name: Finish
      env:
        GH_TOKEN: ${{ secrets.PROMOTED_PUBLIC_DEPLOYER_GITHUB_ACTIONS }}
      run: |
        npm i
        npm run finish
